version: 2.1

test: &test
  name: Setup Virtualenv, install dependencies and test
  command: |
    virtualenv .python
    . .python/bin/activate
    which python
    python -V
    which pip
    pip -V
    pip install -r requirements.txt
    python ./test_pdpyras.py

jobs:

  py3_6:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          <<: *test

  py3_7:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          <<: *test

  py3_8:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          <<: *test

  py3_9:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          <<: *test

  py3_10:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          <<: *test

  py3_11:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          <<: *test

  py3_12:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          <<: *test

  py3_13:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          <<: *test

workflows:
  version: 2.1
  run_tests:
    jobs:
      - py3_6
      - py3_7
      - py3_8
      - py3_9
      - py3_10
      - py3_11
      - py3_12
      - py3_13

