version: 2.1

pip: &pip
  name: Install Pip
  command: |
    sudo apt update && sudo apt install python3-virtualenv
venv: &venv
  name: Setup Virtualenv
  command: |
    virtualenv .python
getenv: &getenv
  name: Get Environment Info
  command: |
    . .python/bin/activate
    which python
    python -V
    which pip
    pip -V
depinst: &depinst
  name: Install Dependencies
  command: |
    . .python/bin/activate
    pip install -r requirements.txt
test: &test
  name: Run Unit Tests
  command: |
    . .python/bin/activate
    python ./test_pdpyras.py

jobs:

  py3_6:
    docker:
      - image: circleci/python:3.6-bullseye
    steps:
      - checkout
      - run:
          <<: *pip
      - run:
          <<: *venv
      - run:
          <<: *getenv
      - run:
          <<: *depinst
      - run:
          <<: *test

  py3_7:
    docker:
      - image: circleci/python:3.7-bullseye
    steps:
      - checkout
      - run:
          <<: *pip
      - run:
          <<: *venv
      - run:
          <<: *getenv
      - run:
          <<: *depinst
      - run:
          <<: *test

  py3_8:
    docker:
      - image: circleci/python:3.8-bullseye
    steps:
      - checkout
      - run:
          <<: *pip
      - run:
          <<: *venv
      - run:
          <<: *getenv
      - run:
          <<: *depinst
      - run:
          <<: *test

  py3_9:
    docker:
      - image: circleci/python:3.9-bullseye
    steps:
      - checkout
      - run:
          <<: *pip
      - run:
          <<: *venv
      - run:
          <<: *getenv
      - run:
          <<: *depinst
      - run:
          <<: *test

  py3_10:
    docker:
      - image: circleci/python:3.10-bullseye
    steps:
      - checkout
      - run:
          <<: *pip
      - run:
          <<: *venv
      - run:
          <<: *getenv
      - run:
          <<: *depinst
      - run:
          <<: *test

  py3_11:
    docker:
      - image: circleci/python:3.11-bullseye
    steps:
      - checkout
      - run:
          <<: *pip
      - run:
          <<: *venv
      - run:
          <<: *getenv
      - run:
          <<: *depinst
      - run:
          <<: *test

workflows: 
  version: 2.1
  run_tests:
    jobs:
      - py3_6
      - py3_7
      - py3_8
      - py3_9
      - py3_10
      - py3_11

